var dataSet = [
  ["大陸地區",101,"上海交通大學",65,"http://www.sjtu.edu.cn/"],
  ["大陸地區",101,"北京大學",82,"http://www.pku.edu.cn/"],
  ["大陸地區",101,"廈門大學",40,"http://www.xmu.edu.cn/"],
  ["日本",101,"大阪大學",35,"http://www.osaka-u.ac.jp/"],
  ["日本",101,"立命館大學",32,"http://www.ritsumei.jp/index_j.html"],
  ["日本",101,"東北大學",30,"http://www.tohoku.ac.jp/en/"],
  ["美國",101,"加州大學柏克萊分校",63,"http://www.berkeley.edu/"],
  ["美國",101,"史丹福大學",56,"http://www.stanford.edu/"],
  ["美國",101,"西來大學",45,"http://www.uwest.edu/site/"],
  ["大韓民國(南韓)",101,"東亞大學",25,"http://www.donga.ac.kr/"],
  ["大韓民國(南韓)",101,"成均館大學",24,"http://www.skku.edu/index_pc.jsp"],
  ["大韓民國(南韓)",101,"又松大學",22,"http://www.wsu.ac.kr/site/main/intro/intro.html"],
  ["德意志聯邦共和國",101,"海德堡大學",51,"http://www.uni-heidelberg.de/"],
  ["德意志聯邦共和國",101,"漢堡大學",29,"http://www.uni-hamburg.de/"],
  ["德意志聯邦共和國",101,"柏林自由大學",19,"http://www.fu-berlin.de/"],
  ["法國",101,"里爾天主教大學",34,"http://www.univ-catholille.fr/"],
  ["法國",101,"里昂大三大學",23,"http://www.univ-lyon3.fr/"],
  ["法國",101,"特魯瓦高等商學院",11,"http://www.educations.com/study-abroad/groupe-esc-troyes-school-of-management/"],
  ["英國",101,"牛津大學哈福特學院",39,"http://www.ox.ac.uk/"],
  ["英國",101,"北安普頓大學",13,"http://www.northampton.ac.uk/"],
  ["英國",101,"愛丁堡大學",10,"http://www.ed.ac.uk/home"],
  ["荷蘭王國",101,"烏特列茲大學",25,"http://www.uu.nl/"],
  ["荷蘭王國",101,"葛洛寧恩大學",21,"http://www.rug.nl/"],
  ["荷蘭王國",101,"萊登大學",8,"http://www.leidenuniv.nl/"],
  ["捷克共和國",101,"布爾諾科技大學",18,"https://www.vutbr.cz/en/"],
  ["捷克共和國",101,"捷克科技大學",11,"http://www.cvut.cz/"],
  ["捷克共和國",101,"哈德克.卡爾威大學",8,"https://www.uhk.cz/en-GB/UHK"],
  ["加拿大",101,"漢堡學院",15,"http://www.humber.ca/"],
  ["加拿大",101,"布洛克大學",11,"http://www.brocku.ca/"],
  ["加拿大",101,"維多利亞大學",10,"http://www.uvic.ca/"],
  ["瑞典王國",101,"林雪平大學",20,"http://www.liu.se/?l=en"],
  ["瑞典王國",101,"皇家理工學院",12,"http://www.kth.se/"],
  ["瑞典王國",101,"查爾默大學",10,"http://www.chalmers.se/en/Pages/default.aspx"],
  ["澳大利亞",101,"迪肯大學",15,"http://www.deakin.edu.au/"],
  ["澳大利亞",101,"昆士蘭大學",10,"http://www.uq.edu.au/"],
  ["澳大利亞",101,"昆士蘭科技大學",8,"https://www.qut.edu.au/"],
  ["香港",101,"香港中文大學",26,"http://www.cuhk.edu.hk/chinese/"],
  ["香港",101,"香港城市大學",15,"http://www.cityu.edu.hk/cityu/index-tc.htm"],
  ["香港",101,"樹仁大學",12,"http://www.hksyu.edu/"],
  ["西班牙王國",101,"馬德里自治大學",9,"http://www.uam.es/ss/Satellite/es/home/"],
  ["西班牙王國",101,"納瓦拉大學",8,"http://www.unav.edu/web/biblioteca"],
  ["西班牙王國",101,"卡斯提亞拉曼查大學",7,"https://www.uclm.es/english/"],
  ["奧地利共和國",101,"林茲大學",20,"http://www.jku.at/content"],
  ["奧地利共和國",101,"茵斯堡大學",15,"http://www.uibk.ac.at/"],
  ["奧地利共和國",101,"維也納大學",8,"http://www.univie.ac.at/"],
  ["泰王國(泰國)",101,"湄州大學",7,"http://www.mju.ac.th/about/mju-about-2004/INDEX.html"],
  ["泰王國(泰國)",101,"曼谷大學",6,"http://www.bu.ac.th/tha/"],
  ["泰王國(泰國)",101,"清邁大學",6,"http://www.cmu.ac.th/"],
  ["新加坡共和國",101,"南洋理工大學",19,"http://www.ntu.edu.sg/Pages/home.aspx"],
  ["新加坡共和國",101,"新加坡國立大學",18,"http://www.nus.edu.sg/"],
  ["新加坡共和國",101,"新加坡管理大學",7,"http://www.smu.edu.sg/"],
  ["馬來西亞",101,"馬來亞大學",13,"https://www.um.edu.my/"],
  ["馬來西亞",101,"馬來西亞新紀元學院",7,"http://www.newera.edu.my/"],
  ["馬來西亞",101,"馬來西亞理工大學(UTM)",2,"http://www.utm.my/"],
  ["芬蘭共和國",101,"阿爾托大學",13,"http://www.aalto.fi/fi/"],
  ["芬蘭共和國",101,"拉瑞爾科技應用大學",4,"https://www.laurea.fi/"],
  ["芬蘭共和國",101,"坦佩利大學",3,"http://www.uta.fi/en/"],
  ["菲律賓共和國",101,"馬尼拉安特雷歐大學",14,"http://www.ateneo.edu/"],
  ["菲律賓共和國",101,"瑪布阿科學技術學院",10,"http://www.mapua.edu.ph/"],
  ["菲律賓共和國",101,"新英格蘭大學",10,"http://www.une.edu.au/"],
  ["大陸地區",102,"復旦大學",99,"http://www.fudan.edu.cn/index.html"],
  ["大陸地區",102,"同濟大學",93,"http://www.tongji.edu.cn/"],
  ["大陸地區",102,"南京大學",84,"http://www.nju.edu.cn/"],
  ["日本",102,"大阪大學",31,"http://www.osaka-u.ac.jp/"],
  ["日本",102,"早稻田大學",27,"http://www.waseda.jp/top/en"],
  ["日本",102,"同志社大學",23,"https://www.doshisha.ac.jp/"],
  ["日本",102,"東北大學",23,"http://www.tohoku.ac.jp/en/"],
  ["美國",102,"西來大學",35,"http://www.uwest.edu/site/"],
  ["美國",102,"天普大學",26,"http://www.temple.edu/"],
  ["美國",102,"波莫納加州州立理工大學",19,"http://www.cpp.edu/"],
  ["大韓民國(南韓)",102,"梨花女子大學",23,"http://www.ewha.ac.kr/mbs/ewhakr/index.jsp"],
  ["大韓民國(南韓)",102,"首爾教育大學",23,"http://www.snue.ac.kr/index_intro.jsp"],
  ["大韓民國(南韓)",102,"成均館大學",22,"http://www.skku.edu/index_pc.jsp"],
  ["德意志聯邦共和國",102,"杜賓根大學",21,"http://www.uni-tuebingen.de/"],
  ["德意志聯邦共和國",102,"慕尼黑工業大學",16,"http://www.tum.de/"],
  ["德意志聯邦共和國",102,"曼漢姆大學",11,"http://www.uni-mannheim.de/1/"],
  ["法國",102,"里昂第三大學",21,"http://www.univ-lyon3.fr/"],
  ["法國",102,"法國雷恩商學院",18,"https://www.esc-rennes.fr/"],
  ["法國",102,"巴黎高等政治學院",10,"http://www.sciencespo.fr/"],
  ["英國",102,"英國劍橋大學",25,"http://www.cam.ac.uk/"],
  ["英國",102,"曼徹斯特大學",12,"http://www.manchester.ac.uk/"],
  ["英國",102,"英國女皇大學",8,"http://www.qub.ac.uk/"],
  ["荷蘭王國",102,"荷蘭萊頓大學",21,"http://www.leidenuniv.nl/"],
  ["荷蘭王國",102,"葛洛寧恩大學",18,"http://www.rug.nl/"],
  ["荷蘭王國",102,"鹿特丹管理學院",7,"http://www.rsm.nl/home/"],
  ["泰國",102,"湄州大學",6,"http://www.mju.ac.th/about/mju-about-2004/INDEX.html"],
  ["泰國",102,"清邁皇家大學",4,"http://www.satitschool.cmru.ac.th/"],
  ["泰國",102,"曼谷大學",3,"http://www.bu.ac.th/tha/"],
  ["西班牙",102,"胡安卡洛斯國王大學",7,"http://www.urjc.es/"],
  ["西班牙",102,"瓦倫西亞科技大學",7,"http://www.upv.es/"],
  ["西班牙",102,"哈恩大學",6,"http://www10.ujaen.es/"],
  ["芬蘭",102,"阿爾托大學",18,"http://www.aalto.fi/fi/"],
  ["芬蘭",102,"拉瑞爾科技應用大學",6,"https://www.laurea.fi/"],
  ["芬蘭",102,"育華斯基里拉大學       ",4,"https://www.jyu.fi/en/"],
  ["香港",102,"香港中文大學",23,"http://www.cuhk.edu.hk/chinese/"],
  ["香港",102,"香港城市大學",17,"http://www.cityu.edu.hk/cityu/index-tc.htm"],
  ["香港",102,"香港大學",16,"https://www.hku.hk/c_index.html"],
  ["捷克共和國",102,"捷克科技大學",18,"http://www.cvut.cz/"],
  ["捷克共和國",102,"奧斯特拉瓦科技大學",11,"https://www.vsb.cz/en"],
  ["捷克共和國",102,"布爾諾科技大學",10,"https://www.vutbr.cz/en/"],
  ["比利時",102,"天主教魯汶大學",11,"http://www.uclouvain.be/index.html"],
  ["比利時",102,"布魯塞爾自由大學",8,"http://www.ulb.ac.be/"],
  ["比利時",102,"安特衛普大學",6,"https://www.uantwerpen.be/nl/"],
  ["加拿大",102,"漢堡學院",15,"http://www.humber.ca/"],
  ["加拿大",102,"紐芬蘭紀念大學",13,"http://www.mun.ca/"],
  ["加拿大",102,"不列顛哥倫比亞大學",12,"http://www.ubc.ca/"],
  ["馬來西亞",102,"馬來亞大學",26,"https://www.um.edu.my/"],
  ["馬來西亞",102,"雙威大學",12,"http://www.sunway.edu.my/"],
  ["馬來西亞",102,"新紀元學院",7,"http://www.newera.edu.my/"],
  ["奧地利",102,"林茲大學",20,"http://www.jku.at/content"],
  ["奧地利",102,"茵斯堡大學",17,"http://www.uibk.ac.at/"],
  ["奧地利",102,"約翰克卜勒大學",5,"http://www.jku.at/content"],
  ["新加坡共和國",102,"南洋理工大學",22,"http://www.ntu.edu.sg/Pages/home.aspx"],
  ["新加坡共和國",102,"新加坡國立大學",19,"http://www.nus.edu.sg/"],
  ["新加坡共和國",102,"新加坡管理大學",9,"http://www.smu.edu.sg/"],
  ["瑞典",102,"林雪平大學",22,"http://www.liu.se/?l=en"],
  ["瑞典",102,"查默斯理工大學",18,"http://www.chalmers.se/en/Pages/default.aspx"],
  ["瑞典",102,"哈勒姆斯塔德大學",7,"http://www.hh.se/"],
  ["澳大利亞",102,"昆士蘭科技大學",13,"https://www.qut.edu.au/"],
  ["澳大利亞",102,"新南威爾斯大學",13,"https://www.unsw.edu.au/"],
  ["澳大利亞",102,"格里菲斯大學",10,"https://www.griffith.edu.au/"],
  ["大陸地區",103,"復旦大學",67,"http://www.fudan.edu.cn/index.html"],
  ["大陸地區",103,"南京大學",56,"http://www.nju.edu.cn/"],
  ["大陸地區",103,"北京大學",47,"http://www.pku.edu.cn/"],
  ["日本",103,"東北大學",22,"http://www.tohoku.ac.jp/en/"],
  ["日本",103,"大阪大學",21,"http://www.osaka-u.ac.jp/ja"],
  ["日本",103,"北海道大學",17,"http://www.hokudai.ac.jp/"],
  ["美國",103,"西來大學",18,"http://www.uwest.edu/site/"],
  ["美國",103,"印第安纳大學-普渡大學維恩堡分校",14,"https://www.ipfw.edu/"],
  ["美國",103,"天普大學",13,"http://www.temple.edu/"],
  ["南韓",103,"梨花女子大學",19,"http://www.ewha.ac.kr/mbs/ewhakr/index.jsp"],
  ["南韓",103,"中央大學",13,"http://www.cau.ac.kr/index.php"],
  ["南韓",103,"東亞大學",12,"http://www.donga.ac.kr/"],
  ["德國",103,"曼漢姆大學",16,"http://www.uni-mannheim.de/1/"],
  ["德國",103,"杜賓根大學",12,"http://www.uni-tuebingen.de/"],
  ["德國",103,"福茲堡應用科技大學",7,"http://www.fhws.de/"],
  ["法國",103,"里昂第三大學",15,"http://www.univ-lyon3.fr/"],
  ["法國",103,"里爾天主教大學",12,"http://www.univ-catholille.fr/"],
  ["法國",103,"特魯瓦高等商學院",9,"http://www.utt.fr/fr/index.html"],
  ["加拿大",103,"曼尼托巴大學",15,"http://umanitoba.ca/"],
  ["加拿大",103,"漢堡學院",10,"http://www.humber.ca/"],
  ["加拿大",103,"西門菲沙大學",6,"http://www.sfu.ca/"],
  ["荷蘭",103,"葛洛寧恩大學",10,"http://www.rug.nl/gradschooleb/index"],
  ["荷蘭",103,"萊登大學",9,"http://www.leidenuniv.nl/"],
  ["荷蘭",103,"漢斯應用科技大學",5,"https://www.hanze.nl/eng/"],
  ["英國",103,"蘭卡斯特大學",5,"http://www.lancaster.ac.uk/"],
  ["英國",103,"倫敦政經學院",4,"http://www.lse.ac.uk/home.aspx"],
  ["英國",103,"桑德蘭大學",4,"http://www.sunderland.ac.uk/"],
  ["西班牙",103,"瓦倫西亞科技大學",6,"http://www.upv.es/"],
  ["西班牙",103,"薩拉曼卡大學",6,"http://www.usal.es/webusal/"],
  ["西班牙",103,"哈恩大學",5,"http://www10.ujaen.es/"],
  ["香港",103,"香港城市大學",14,"http://www.cityu.edu.hk/cityu/index-tc.htm"],
  ["香港",103,"香港中文大學",12,"http://www.cuhk.edu.hk/chinese/"],
  ["香港",103,"香港大學",9,"https://www.hku.hk/c_index.html"],
  ["奧地利共和國",103,"林茲大學",11,"http://www.jku.at/content"],
  ["奧地利共和國",103,"茵斯堡大學",7,"http://www.uibk.ac.at/"],
  ["奧地利共和國",103,"維也納大學",6,"http://www.univie.ac.at/"],
  ["瑞典",103,"林雪平大學",11,"http://www.liu.se/?l=en"],
  ["瑞典",103,"哈勒姆斯塔德",7,"http://www.hh.se/"],
  ["瑞典",103,"查默斯理工大學",6,"http://www.chalmers.se/en/Pages/default.aspx"],
  ["澳大利亞",103,"昆士蘭科技大學",10,"https://www.qut.edu.au/"],
  ["澳大利亞",103,"南天大學",4,"http://www.nantien.edu.au/"],
  ["澳大利亞",103,"昆士蘭大學",3,"http://www.uq.edu.au/"],
  ["新加坡共和國",103,"新加坡國立大學",11,"http://www.nus.edu.sg/"],
  ["新加坡共和國",103,"南洋理工大學",9,"http://www.ntu.edu.sg/Pages/home.aspx"],
  ["新加坡共和國",103,"新加坡管理大學",7,"http://www.smu.edu.sg/"],
  ["波蘭",103,"華沙經濟大學",5,"http://www.sgh.waw.pl/index_en.html"],
  ["波蘭",103,"華沙大學",4,"http://www.uw.edu.pl/"],
  ["波蘭",103,"亞捷隆大學",4,"http://www.uj.edu.pl/"],
  ["芬蘭",103,"阿爾托大學",6,"http://www.aalto.fi/fi/"],
  ["芬蘭",103,"JAMK應用科技大學",3,"www.jamk.fi/fi/Etusivu"],
  ["芬蘭",103,"于韋斯屈萊大學",3,"https://www.jyu.fi/"],
  ["瑞士",103,"蘇黎世應用科學大學",8,"http://www.sml.zhaw.ch/en"],
  ["瑞士",103,"聖加崙大學",4,"http://www.unisg.ch/"],
  ["瑞士",103,"蘇黎世大學",3,"http://www.uzh.ch/index.html"],
  ["瑞士",103,"洛桑大學",3,"http://www.unil.ch/index.html"],
  ["馬來西亞",103,"馬來亞大學",21,"https://www.um.edu.my/"],
  ["馬來西亞",103,"拉曼大學",1,"http://www.tarc.edu.my/"]
];

$(document).ready(function() {
    $('#example').DataTable( {
        data: dataSet,
        "columnDefs": [
            { "visible": false }
        ],
        "scrollY":        "600px",
        "scrollCollapse": true,
        "paging":         false,
        "order": [[ 2, 'asc' ]],
        columns: [
            { title: "國家" },
            { title: "年度" },
            { title: "學校" },
            { title: "人數" },
            { title: "網址" }
        ]
    } );
} );

